config/routes.rb
Rails.application.routes.draw do
  
  resources :searches
  resources :outputs
  get '/list_outputs', to: 'outputs#list_outputs'
  resources :partidas
  resources :conceptos
  get     'login'  => 'sessions#new'
  post    'login'  => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  root    'static_pages#main'

  resources :capitulos
  resources :inputs
  get '/list_inputs', to: 'inputs#list_inputs'
  resources :suppliers
  resources :products
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capitulo.rb
class Capitulo < ApplicationRecord
  has_many :conceptos, dependent: :destroy

  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/concepto.rb
class Concepto < ApplicationRecord
  belongs_to :capitulo
  has_many :partidas, dependent: :destroy

  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/input.rb
class Input < ApplicationRecord
  belongs_to :product
  belongs_to :supplier
  # belongs_to :user
end

app/models/output.rb
class Output < ApplicationRecord
  belongs_to :product
  # belongs_to :user
  validate :only_take_existing

  private

    def only_take_existing
      producto = Product.find(product_id)
      new_stock = producto.stock - quantity
      if new_stock < 0
        errors.add(:quantity, ": No hay suficientes #{producto.name} para entregar la cantidad solicitada.")
      else
        producto.update(stock: new_stock)
      end
    end
    
end

app/models/partida.rb
class Partida < ApplicationRecord
  belongs_to :concepto
  
  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :inputs, dependent: :destroy
  has_many :outputs, dependent: :destroy
  belongs_to :supplier
  # has_many :suppliers
  def add_to_stock(new_items)
    
    self.update(stock: self.stock + new_items)
  end
  
  def take_from_stock(items)
    result = self.stock - items
    self.update(stock: (result < 0) ? 0 : result)
  end
  
end

app/models/search.rb
class Search < ApplicationRecord

  def search_products
    products = Product.all

    products = products.where([ 'code LIKE ?', code ]) if code.present?
    products = products.where(['name LIKE ?', name]) if name.present?
    products = products.where(['brand LIKE ?', brand]) if brand.present?
    products = products.where( supplier_id: supplier_id.to_i ) if supplier_id.present?
    products = products.where( capitulo_id: capitulo_id.to_i ) if capitulo_id.present?
    products = products.where( concepto_id: concepto_id.to_i ) if concepto_id.present?
    products = products.where( partida_id: partida_id.to_i ) if partida_id.present?

    return products
  end
  
  def self.clean_up_searches
    Search.delete_all
  end
  
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :inputs, dependent: :destroy
  has_many :products, dependent: :destroy
  # has_many :products, through: :inputs
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  enum access_level: { user: 0, admin: 1, owner: 2 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 250 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    # Beware: this uniqueness code IS NOT ENOUGH
                    #  Need to add Database index, migration DONE

  validates :password, length: { minimum: 8 }
  has_secure_password
  # has_many :inputs

  # Returns the hash digest of the given string
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  before_action :set_input, only: %i[ show edit update destroy ]
  before_action :options

  # GET /inputs or /inputs.json
  def index
    @inputs = Input.all
    # new_input
  end

  # GET /inputs/1 or /inputs/1.json
  def show
  end

  # GET /inputs/new
  def new
    new_input
  end

  # GET /list_inputs
  def list_inputs
    @input_list = params[:input] || []
    new_input
  end
  

  # GET /inputs/1/edit
  def edit
  end

  # POST /inputs or /inputs.json
  def create
    # @inputs = Input.all
    new_input
    @input.user_id = @user.id
    # params[:input][:user_id] = current_user.id
    respond_to do |format|
      if @input.save
        @product.add_to_stock(@input.quantity)
        format.js
        # format.html { redirect_to @input, notice: "Input was successfully created." }
        # format.json { render :show, status: :created, location: @input }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inputs/1 or /inputs/1.json
  def update
    respond_to do |format|
      if @input.update(input_params)
        format.html { redirect_to @input, notice: "Input was successfully updated." }
        format.json { render :show, status: :ok, location: @input }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputs/1 or /inputs/1.json
  def destroy
    @input.destroy
    respond_to do |format|
      format.html { redirect_to inputs_url, notice: "Input was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_input
      @input = Input.find(params[:id])
    end

    def new_input
      if action_name == 'create'
        @input = Input.new(input_params)
        @product = Product.find_by(id: @input.product_id)
      else
        @input = Input.new
        @products = Product.all
      end
      @suppliers = Supplier.all
     
      @user = current_user
    end
    

    # Only allow a list of trusted parameters through.
    def input_params
      params.require(:input).permit(:input_date, :invoice, :price, :quantity, :location, :product_id, :supplier_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capitulos_helper.rb
module CapitulosHelper
end

app/helpers/conceptos_helper.rb
module ConceptosHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/helpers/partidas_helper.rb
module PartidasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged in user (if any)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Returns current user access level
  def current_access_level
    case @current_user.access_level
    when "user"
      return 0
    when "admin"
      return 1
    when "owner"
      return 2
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inputs/_form.html.erb
<%= form_with(model: input, id: "new-input", local: false) do |form| %>
  <% if input.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(input.errors.count, "error") %> prohibited this input from being saved:</h2>

      <ul>
        <% input.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   
  <div style="padding-top: 50px;padding-bottom: 30px;">
    <table class="show-table">
      <tr>
        <td>Proveedor:</td>
        <td colspan="3"><%= form.collection_select :supplier_id, @suppliers, :id, :name, { :prompt => "Proveedor sugerido"}%></td>
      </tr>
      <tr>
        <td>Factura:</td>
        <td><%= form.text_field :invoice %></td>
        <td>Fecha:</td>
        <td><%= form.date_field :input_date %></td>
      </tr>
    </table>
    <div class="void-space">
      <br>
    </div>
    <table class="index-table">
      <thead>
        <tr>
          <td>Producto</td>
          <td>Cantidad</td>
          <td>Ubicación</td>
          <td>Acción</td>
        </tr>
      </thead>
      <tbody>
        <%  %>
        <tr>
          <td><%= form.collection_select :product_id, @products, :id, :name, { :prompt => "Producto"}%></td>
          <td><%= form.text_field :quantity %></td>
          <td><%= form.text_field :location %></td>
          <% form.hidden_field :user_id, value: current_user.id %>
          <td><%= form.submit "Guardar", class: "btn success" %></td>
        </tr>
      </tbody>
    </table>
  </div>

<% end %>

app/views/inputs/_input.html.erb
<tr>
  <td><%= input.product.name %></td>
  <td><%= input.quantity %></td>
  <td><%= input.location %></td>
  <td class="botones"><%= link_to 'Destroy', input, class: "btn info", method: :delete, data: { confirm: '¿Confirma la eliminación del registro?' } %></td>
</tr>

app/views/inputs/_inputs.html.erb
<tr>
  <td><%= input.product.name %></td>
  <td><%= input.price %></td>
  <td><%= input.quantity %></td>
  <td><%= (input.price * input.quantity).round(2)%>
  <td><%= input.location %></td>
  <td class="botones"><%= link_to 'Destroy', input, class: "btn info", method: :delete, data: { confirm: '¿Confirma la eliminación del registro?' } %></td>
</tr>

app/views/inputs/create.js.erb
// Render input
var body = document.getElementById("input-list");
body.innerHTML = "<%= j render @input %>" + body.innerHTML;

//Clear and Focus input form
var input = document.getElementById("input_product_id");
input.value = '';
input.focus();

app/views/inputs/edit.html.erb
<h1>Editing Input</h1>

<%= render 'form', input: @input %>

<%= link_to 'Show', @input %> |
<%= link_to 'Back', inputs_path %>

app/views/inputs/index.html.erb
<div>
  <h1>Entradas al almacén</h1>
</div>

<div class="index-division">
  <table class="index-table">
    <thead>
          <tr>
            <td>Producto</td>
            <td>Proveedor</td>
            <td>Fecha de Entrada</td>
            <td>Cantidad</td>
            <td>Ubicación</td>
            <td>Acción</td>
          </tr>
    </thead>
    <tbody>
      <% @inputs.each do |input| %>
        <tr>
          <td><%= input.product.name %></td>
          <td><%= input.product.supplier.name%></td>
          <td><%= input.input_date.strftime("%d-%_m-%Y") %></td>
          <td><%= input.quantity %></td>
          <td><%= input.location %></td>
          <td class="botones"><%= link_to 'Destroy', input, class: "btn info", method: :delete, data: { confirm: '¿Confirma la eliminación del registro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Registrar Entradas', list_inputs_path %>

<%= content_for :footer do %>
  <p id="notice"><%= notice %></p>
<%  end %>

app/views/inputs/list_inputs.html.erb
<h1>Registro de entradas al almacén</h1>

<%= render 'form', input: @input %>

<table class="index-table">
  <tbody id='input-list'>
    <% @input_list.each do |input| %>
      <%= render 'inputs', input: input %>
    <% end %>
  </tbody>
</table>

<br>

<%= content_for :footer do %>
  <p id="notice"><%= notice %></p>
<%  end %>

app/views/inputs/new.html.erb
<h1>Captura de entradas al almacén</h1>

<%= render 'form', input: @input %>

<%= render 'inputs', inputs: @inputs %>

<%= link_to 'Regresar al Inventario', inputs_path %>

app/views/inputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Input date:</strong>
  <%= @input.input_date %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @input.invoice %>
</p>

<p>
  <strong>Price:</strong>
  <%= @input.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @input.quantity %>
</p>

<p>
  <strong>Location:</strong>
  <%= @input.location %>
</p>

<p>
  <strong>Product:</strong>
  <%= @input.product_id %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @input.supplier_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @input.user_id %>
</p>

<%= link_to 'Edit', edit_input_path(@input) %> |
<%= link_to 'Back', inputs_path %>