config/routes.rb
Rails.application.routes.draw do
  
  resources :searches
  resources :outputs
  get '/list_outputs', to: 'outputs#list_outputs'
  resources :partidas
  resources :conceptos
  get     'login'  => 'sessions#new'
  post    'login'  => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  root    'static_pages#main'

  resources :capitulos
  resources :inputs
  get '/list_inputs', to: 'inputs#list_inputs'
  resources :suppliers
  resources :products
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capitulo.rb
class Capitulo < ApplicationRecord
  has_many :conceptos, dependent: :destroy

  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/concepto.rb
class Concepto < ApplicationRecord
  belongs_to :capitulo
  has_many :partidas, dependent: :destroy

  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/input.rb
class Input < ApplicationRecord
  belongs_to :product
  belongs_to :supplier
  # belongs_to :user
end

app/models/output.rb
class Output < ApplicationRecord
  belongs_to :product
  # belongs_to :user
  validate :only_take_existing

  private

    def only_take_existing
      producto = Product.find(product_id)
      new_stock = producto.stock - quantity
      if new_stock < 0
        errors.add(:quantity, ": No hay suficientes #{producto.name} para entregar la cantidad solicitada.")
      else
        producto.update(stock: new_stock)
      end
    end
    
end

app/models/partida.rb
class Partida < ApplicationRecord
  belongs_to :concepto
  
  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :inputs, dependent: :destroy
  has_many :outputs, dependent: :destroy
  belongs_to :supplier
  # has_many :suppliers
  def add_to_stock(new_items)
    
    self.update(stock: self.stock + new_items)
  end
  
  def take_from_stock(items)
    result = self.stock - items
    self.update(stock: (result < 0) ? 0 : result)
  end
  
end

app/models/search.rb
class Search < ApplicationRecord

  def search_products
    products = Product.all

    products = products.where([ 'code LIKE ?', code ]) if code.present?
    products = products.where(['name LIKE ?', name]) if name.present?
    products = products.where(['brand LIKE ?', brand]) if brand.present?
    products = products.where( supplier_id: supplier_id.to_i ) if supplier_id.present?
    products = products.where( capitulo_id: capitulo_id.to_i ) if capitulo_id.present?
    products = products.where( concepto_id: concepto_id.to_i ) if concepto_id.present?
    products = products.where( partida_id: partida_id.to_i ) if partida_id.present?

    return products
  end
  
  def self.clean_up_searches
    Search.delete_all
  end
  
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :inputs, dependent: :destroy
  has_many :products, dependent: :destroy
  # has_many :products, through: :inputs
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  enum access_level: { user: 0, admin: 1, owner: 2 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 250 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    # Beware: this uniqueness code IS NOT ENOUGH
                    #  Need to add Database index, migration DONE

  validates :password, length: { minimum: 8 }
  has_secure_password
  # has_many :inputs

  # Returns the hash digest of the given string
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :options

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :access_level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capitulos_helper.rb
module CapitulosHelper
end

app/helpers/conceptos_helper.rb
module ConceptosHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/helpers/partidas_helper.rb
module PartidasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged in user (if any)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Returns current user access level
  def current_access_level
    case @current_user.access_level
    when "user"
      return 0
    when "admin"
      return 1
    when "owner"
      return 2
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <%= content_for :footer do %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
  <div style="padding-top: 50px;padding-bottom: 30px;">
    <table class="show-table">
      <tr>
        <td><%= form.label :name, 'Nombre:' %></td>
        <td><%= form.text_field :name %></td>
      </tr>
      <tr>
        <td><%= form.label :email %></td>
        <td><%= form.text_field :email %></td>
      </tr>
      <tr>
        <td><%= form.label :password %></td>
        <td><%= form.password_field :password %></td>
      </tr>
      <tr>
        <td><%= form.label :password_confirmation, "Confirmación" %></td>
        <td><%= form.password_field :password_confirmation %></td>
      </tr>
      <tr>
        <td><%= form.label :access_level, "Nivel de Accesso" %></td>
        <td><%= form.select :access_level, { user: 'user', admin: 'admin', owner: 'owner' } %></td>
      </tr>
      <tr>
        <td  colspan="2" style="text-align: center;"><%= form.submit class: "btn-lg success" %></td>
      </tr>
    </table>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Modificar datos de Usuario</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

<% content_for :footer do %>
  <p id="notice"><%= notice %>
<% end %>

app/views/users/index.html.erb
<h1>Usuarios</h1>


<div class="index-division">
  <table class="index-table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Email</th>
        <th>Nivel</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.access_level %></td>
          <td><%= link_to 'Show', user, class: "btn info" %></td>
          <td><%= link_to 'Edit', edit_user_path(user), class: "btn info" %></td>
          <td><%= link_to 'Destroy', user, class: "btn info", method: :delete, data: { confirm: '¿Está de acuerdo en eliminar al usuario?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


 <br>

 <%= link_to 'Usuario Nuevo', new_user_path, class: "btn-lg success" %>

<% content_for :footer do %>
  <p id="notice"><%= notice %></p>
<% end %>

app/views/users/new.html.erb
<h1>Usuario Nuevo</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

<% content_for :footer do %>
  <p id="notice"><%= notice %>
<% end %>

app/views/users/show.html.erb
<div class="show-division-head">
  <table class="show-table">
    <tr>
      <td>Nombre:</td>
      <td><strong><%= @user.name %></strong></td>
    </tr>
    <tr>
      <td>Email:</td>
      <td><strong><%= @user.email %></strong></td>
    </tr>
    <tr>
      <td>Nivel:</td>
      <td><strong><%= @user.access_level %></strong></td>
    </tr>
  </table>
</div>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>

<% content_for :footer do %>
  <p id="notice"><%= notice %>
<% end %>