config/routes.rb
Rails.application.routes.draw do
  
  resources :searches
  resources :outputs
  get '/list_outputs', to: 'outputs#list_outputs'
  resources :partidas
  resources :conceptos
  get     'login'  => 'sessions#new'
  post    'login'  => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  root    'static_pages#main'

  resources :capitulos
  resources :inputs
  get '/list_inputs', to: 'inputs#list_inputs'
  resources :suppliers
  resources :products
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capitulo.rb
class Capitulo < ApplicationRecord
  has_many :conceptos, dependent: :destroy

  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/concepto.rb
class Concepto < ApplicationRecord
  belongs_to :capitulo
  has_many :partidas, dependent: :destroy

  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/input.rb
class Input < ApplicationRecord
  belongs_to :product
  belongs_to :supplier
  # belongs_to :user
end

app/models/output.rb
class Output < ApplicationRecord
  belongs_to :product
  # belongs_to :user
  validate :only_take_existing

  private

    def only_take_existing
      producto = Product.find(product_id)
      new_stock = producto.stock - quantity
      if new_stock < 0
        errors.add(:quantity, ": No hay suficientes #{producto.name} para entregar la cantidad solicitada.")
      else
        producto.update(stock: new_stock)
      end
    end
    
end

app/models/partida.rb
class Partida < ApplicationRecord
  belongs_to :concepto
  
  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :inputs, dependent: :destroy
  has_many :outputs, dependent: :destroy
  belongs_to :supplier
  # has_many :suppliers
  def add_to_stock(new_items)
    
    self.update(stock: self.stock + new_items)
  end
  
  def take_from_stock(items)
    result = self.stock - items
    self.update(stock: (result < 0) ? 0 : result)
  end
  
end

app/models/search.rb
class Search < ApplicationRecord

  def search_products
    products = Product.all

    products = products.where([ 'code LIKE ?', code ]) if code.present?
    products = products.where(['name LIKE ?', name]) if name.present?
    products = products.where(['brand LIKE ?', brand]) if brand.present?
    products = products.where( supplier_id: supplier_id.to_i ) if supplier_id.present?
    products = products.where( capitulo_id: capitulo_id.to_i ) if capitulo_id.present?
    products = products.where( concepto_id: concepto_id.to_i ) if concepto_id.present?
    products = products.where( partida_id: partida_id.to_i ) if partida_id.present?

    return products
  end
  
  def self.clean_up_searches
    Search.delete_all
  end
  
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :inputs, dependent: :destroy
  has_many :products, dependent: :destroy
  # has_many :products, through: :inputs
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  enum access_level: { user: 0, admin: 1, owner: 2 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 250 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    # Beware: this uniqueness code IS NOT ENOUGH
                    #  Need to add Database index, migration DONE

  validates :password, length: { minimum: 8 }
  has_secure_password
  # has_many :inputs

  # Returns the hash digest of the given string
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[ show edit update destroy ]
  before_action :options

  # GET /suppliers or /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1 or /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers or /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: "Supplier was successfully created." }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1 or /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: "Supplier was successfully updated." }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1 or /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: "Supplier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supplier_params
      params.require(:supplier).permit(:name, :phone, :email, :address, :postal_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capitulos_helper.rb
module CapitulosHelper
end

app/helpers/conceptos_helper.rb
module ConceptosHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/helpers/partidas_helper.rb
module PartidasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged in user (if any)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Returns current user access level
  def current_access_level
    case @current_user.access_level
    when "user"
      return 0
    when "admin"
      return 1
    when "owner"
      return 2
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier) do |form| %>
  <%= content_for :footer do %>
    <% if supplier.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(supplier.errors.count, "error") %> Impidieron guardar este registro:</h2>
        <ul>
          <% supplier.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
  <div style="padding-top: 50px;padding-bottom: 30px;">
    <table class="show-table">
      <tr>
        <td><%= form.label :id, "Código:" %></td>
        <% if action_name == "new" %>
          <td><%= Supplier.maximum(:id) + 1 %></td>
        <% else %>
          <td><%= form.text_field :id, disabled: true %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= form.label :name, "Nombre:" %></td>
        <td><%= form.text_field :name %></td>
      </tr>
      <tr>
        <td><%= form.label :phone, "Teléfono:" %></td>
        <td><%= form.text_field :phone %></td>
      </tr>
      <tr>
        <td><%= form.label :email %></td>
        <td><%= form.text_field :email %></td>
      </tr>
      <tr>
        <td><%= form.label :address, "Dirección:" %></td>
        <td><%= form.text_area :address %></td>
      </tr>
      <tr>
        <td><%= form.label :postal_code, "Código Postal:" %></td>
        <td><%= form.text_field :postal_code %></td>
      </tr>
      <tr>
        <td  colspan="2" style="text-align: center;"><%= form.submit class: "btn-lg success" %></td>
      </tr>
    </table>
  </div>
 
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editing Supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
  <h1>Proveedores</h1>

<div class="index-division">
  <table class="index-table">
    <thead>
      <tr>
        <th>Código</th>
        <th>Nombre</th>
        <th>Teléfono</th>
        <th>Email</th>
        <th>Dirección</th>
        <th>C. P.</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td><%= supplier.id %></td>
          <td><%= supplier.name %></td>
          <td><%= supplier.phone %></td>
          <td><%= supplier.email %></td>
          <td><%= supplier.address %></td>
          <td><%= supplier.postal_code %></td>
          <td class="botones"><%= link_to 'Show', supplier, class: "btn info" %></td>
          <td class="botones"><%= link_to 'Edit', edit_supplier_path(supplier), class: "btn info" %></td>
          <td class="botones"><%= link_to 'Destroy', supplier, class: "btn info", method: :delete, data: { confirm: '¿Está de acuerdo en eliminar al proveedor?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <br>

  <%= link_to 'Proveedor nuevo', new_supplier_path, class: "btn-lg success" %>


<% content_for :footer do %>
  <p id="notice"><%= notice %></p>
<% end %>

app/views/suppliers/new.html.erb
<h1>New Supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<div class="show-division-head">
  <table class="show-table">
    <tr>
      <td>Código:</td>
      <td><strong><%= @supplier.id %></strong></td>
    </tr>
    <tr>
      <td>Nombre:</td>
      <td><strong><%= @supplier.name %></strong></td>
    </tr>
    <tr>
      <td>Teléfono:</td>
      <td><strong><%= @supplier.phone %></strong></td>
    </tr>
    <tr>
      <td>Email:</td>
      <td><strong><%= @supplier.email %></strong></td>
    </tr>
    <tr>
      <td>Dirección:</td>
      <td><strong><%= @supplier.address %></strong></td>
    </tr>
    <tr>
      <td>Código Postal:</td>
      <td><strong><%= @supplier.postal_code %></strong></td>
    </tr>
  </table>
</div>

<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>

<% content_for :footer do %>
  <p id="notice"><%= notice %></p>
<% end %>