config/routes.rb
Rails.application.routes.draw do
  
  resources :searches
  resources :outputs
  get '/list_outputs', to: 'outputs#list_outputs'
  resources :partidas
  resources :conceptos
  get     'login'  => 'sessions#new'
  post    'login'  => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  root    'static_pages#main'

  resources :capitulos
  resources :inputs
  get '/list_inputs', to: 'inputs#list_inputs'
  resources :suppliers
  resources :products
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capitulo.rb
class Capitulo < ApplicationRecord
  has_many :conceptos, dependent: :destroy

  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/concepto.rb
class Concepto < ApplicationRecord
  belongs_to :capitulo
  has_many :partidas, dependent: :destroy

  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/input.rb
class Input < ApplicationRecord
  belongs_to :product
  belongs_to :supplier
  # belongs_to :user
end

app/models/output.rb
class Output < ApplicationRecord
  belongs_to :product
  # belongs_to :user
  validate :only_take_existing

  private

    def only_take_existing
      producto = Product.find(product_id)
      new_stock = producto.stock - quantity
      if new_stock < 0
        errors.add(:quantity, ": No hay suficientes #{producto.name} para entregar la cantidad solicitada.")
      else
        producto.update(stock: new_stock)
      end
    end
    
end

app/models/partida.rb
class Partida < ApplicationRecord
  belongs_to :concepto
  
  def mix_clave_desc
    "#{clave} - #{description}"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :inputs, dependent: :destroy
  has_many :outputs, dependent: :destroy
  belongs_to :supplier
  # has_many :suppliers
  def add_to_stock(new_items)
    
    self.update(stock: self.stock + new_items)
  end
  
  def take_from_stock(items)
    result = self.stock - items
    self.update(stock: (result < 0) ? 0 : result)
  end
  
end

app/models/search.rb
class Search < ApplicationRecord

  def search_products
    products = Product.all

    products = products.where([ 'code LIKE ?', code ]) if code.present?
    products = products.where(['name LIKE ?', name]) if name.present?
    products = products.where(['brand LIKE ?', brand]) if brand.present?
    products = products.where( supplier_id: supplier_id.to_i ) if supplier_id.present?
    products = products.where( capitulo_id: capitulo_id.to_i ) if capitulo_id.present?
    products = products.where( concepto_id: concepto_id.to_i ) if concepto_id.present?
    products = products.where( partida_id: partida_id.to_i ) if partida_id.present?

    return products
  end
  
  def self.clean_up_searches
    Search.delete_all
  end
  
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :inputs, dependent: :destroy
  has_many :products, dependent: :destroy
  # has_many :products, through: :inputs
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  enum access_level: { user: 0, admin: 1, owner: 2 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 250 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    # Beware: this uniqueness code IS NOT ENOUGH
                    #  Need to add Database index, migration DONE

  validates :password, length: { minimum: 8 }
  has_secure_password
  # has_many :inputs

  # Returns the hash digest of the given string
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
end

app/controllers/outputs_controller.rb
class OutputsController < ApplicationController
  before_action :set_output, only: [:show, :edit, :update, :destroy]
  before_action :options

  # GET /outputs
  def index
    @outputs = Output.all
  end

  # GET /outputs/1
  def show
  end

  # GET /outputs/new
  def new
    new_output
  end

  # GET /list_outputs
  def list_outputs
    @output_list = params[:output] || []
    new_output
  end

  # GET /outputs/1/edit
  def edit
  end

  # POST /outputs
  def create
    new_output
    @output.user_id = @user.id
    
    respond_to do |format|
      if @output.save
        format.js
      else
        format.html { render :new }
      end      
    end

  end

  # PATCH/PUT /outputs/1
  def update
    if @output.update(output_params)
      redirect_to @output, notice: 'Output was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /outputs/1
  def destroy
    @output.destroy
    redirect_to outputs_url, notice: 'Output was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_output
      @output = Output.find(params[:id])
    end

    def new_output
      if action_name == 'create'
        @output = Output.new(output_params)
        @product = Product.find_by(id: @output.product_id)
      else
        @output = Output.new
        @products = Product.all
      end
      @suppliers = Supplier.all
      
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def output_params
      params.require(:output).permit(:output_date, :invoice, :quantity, :price, :receiving_area, :receiving_person, :product_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capitulos_helper.rb
module CapitulosHelper
end

app/helpers/conceptos_helper.rb
module ConceptosHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/helpers/partidas_helper.rb
module PartidasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged in user (if any)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Returns current user access level
  def current_access_level
    case @current_user.access_level
    when "user"
      return 0
    when "admin"
      return 1
    when "owner"
      return 2
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/outputs/_form.html.erb
<%= form_with(model: @output, id: "new-output", local: false) do |form| %>
  <% if @output.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@output.errors.count, "error") %> prohibited this output from being saved:</h2>

      <ul>
        <% @output.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="index-division">
    <table class="show-table">
      <tr>
        <td colspan="2">Nombre de quién recibe:</td>
        <td colspan="2"><%= form.text_field :receiving_person %></td>
      </tr>
      <tr>
        <td colspan="2">Área que recibe:</td>
        <td colspan="2"><%= form.text_field :receiving_area %></td>
      </tr>
      <tr>
        <td>Referencia:</td>
        <td><%= form.text_field :invoice %></td>
        <td>Fecha:</td>
        <td><%= form.date_field :output_date %></td>
      </tr>
    </table>
    <div class="void-space">
      <br>
    </div>
    <table class="index-table">
      <thead>
        <tr>
          <td>Producto</td>
          <td>Cantidad</td>
          <td>Acción</td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= form.collection_select :product_id, @products, :id, :name, { :prompt => "Producto"}%></td>
          <td><%= form.text_field :quantity %></td>
          <% form.hidden_field :user_id, value: current_user.id %>
          <td><%= form.submit "Guardar", class: "btn success" %></td>
        </tr>
      </tbody>
    </table>
  </div>

<% end %>

app/views/outputs/_output.html.erb
<tr>
  <td><%= output.product.name %></td>
  <td><%= output.output_date.strftime("%d-%m-%Y") %></td>
  <td><%= output.invoice %></td>
  <td><%= output.quantity %></td>
  <td><%= output.price %></td>
  <td><%= output.receiving_area %></td>
  <td><%= output.receiving_person %></td>
  
  <td><%= User.find(output.user_id).name %></td>
  <td class="botones"><%= link_to 'Destroy', output, class: "btn info", method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/outputs/create.js.erb
// Render input
var body = document.getElementById("output-list");
body.innerHTML = "<%= j render @output %>" + body.innerHTML;

//Clear and Focus input form
var input = document.getElementById("output_product_id");
input.value = '';
input.focus();

app/views/outputs/edit.html.erb
<h1>Editing Output</h1>

<%= render 'form', output: @output %>

<%= link_to 'Show', @output %> |
<%= link_to 'Back', outputs_path %>

app/views/outputs/index.html.erb
<h1>Outputs</h1>

<div class="index-division">
  <table class="index-table">
    <thead>
      <tr>
        <th>Producto</th>
        <th>Fecha de Salida</th>
        <th>Referencia</th>
        <th>Cantidad</th>
        <th>Area Receptora</th>
        <th>Receptor</th>
        <th>Entregó</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @outputs.each do |output| %>
        <tr>
          <td><%= output.product.name %></td>
          <td><%= output.output_date %></td>
          <td><%= output.invoice %></td>
          <td><%= output.quantity %></td>
          <td><%= output.receiving_area %></td>
          <td><%= output.receiving_person %></td>
          <td><%= User.find(output.user_id).name %></td>
          <td class="botones"><%= link_to 'Destroy', output, class: "btn info", method: :delete, data: { confirm: '¿Confirma la eliminación del registro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Registrar Salidas', list_outputs_path, class: "btn-lg success" %>

<% content_for :footer do %>
  <p id="notice"><%= notice %></p>
<% end %>

app/views/outputs/list_outputs.html.erb
<h1>Registro de salidas de almacén</h1>

<%= render 'form', input: @output %>

<table class="index-table">
  <tbody id='output-list'>
    <% @output_list.each do |output| %>
      <%= render 'outputs', output: output %>
    <% end %>
  </tbody>
</table>

<br>

<%= content_for :footer do %>
  <p id="notice"><%= notice %></p>
<%  end %>

app/views/outputs/new.html.erb
<h1>New Output</h1>

<%= render 'form', output: @output %>

<%= link_to 'Back', outputs_path %>

app/views/outputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Output date:</strong>
  <%= @output.output_date %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @output.invoice %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @output.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @output.price %>
</p>

<p>
  <strong>Receiving area:</strong>
  <%= @output.receiving_area %>
</p>

<p>
  <strong>Receiving person:</strong>
  <%= @output.receiving_person %>
</p>

<p>
  <strong>Product:</strong>
  <%= @output.product_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @output.user_id %>
</p>

<%= link_to 'Edit', edit_output_path(@output) %> |
<%= link_to 'Back', outputs_path %>